{
 "title": "Manticore",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(manticore_qcache_thresh_microseconds, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RAM-resident index part (MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(manticore_ram_bytes{pod=\"$pod\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Index files size (MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(manticore_disk_bytes{pod=\"$pod\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Found rows by queries for last 1 minute",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(manticore_found_rows_1min{pod=\"$pod\" , type=\"avg\"})"
    }
   ]
  },
  {
   "title": "Indexed documents size (MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(manticore_indexed_bytes{pod=\"$pod\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Query count (last 1 min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(manticore_query_time_1min{pod=\"$pod\",type=\"queries\"}[1m])) by (index)",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Search quereis per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "rate(manticore_command_search_count{pod=\"$pod\"}[10m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connection count  per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rate(manticore_connections_count{pod=\"$pod\"}[10m])",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "Total RAM-resident index part (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(manticore_ram_bytes{pod=\"$pod\"})/1024/1024 ",
     "legendFormat": "RAM index part"
    },
    {
     "expr": "sum(manticore_indexed_bytes{pod=\"$pod\"})/1024/1024",
     "legendFormat": "Indexex docs"
    },
    {
     "expr": "sum(manticore_qcache_used_bytes{pod=\"$pod\"})/1024/1024",
     "legendFormat": "Query cache"
    }
   ]
  },
  {
   "title": "Commands per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(manticore_command_insert_count{pod=\"$pod\"}[1m]))",
     "legendFormat": "insert"
    },
    {
     "expr": "sum(rate(manticore_command_replace_count{pod=\"$pod\"}[1m]))",
     "legendFormat": "replace"
    },
    {
     "expr": "sum(increase(manticore_command_commit_count{pod=\"$pod\"}[1m]))",
     "legendFormat": "commit"
    },
    {
     "expr": "sum(rate(manticore_command_suggest_count{pod=\"$pod\"}[1m]))",
     "legendFormat": "suggest"
    },
    {
     "expr": "sum(rate(manticore_command_callpq_count{pod=\"$pod\"}[1m]))",
     "legendFormat": "callpq"
    },
    {
     "expr": "sum(rate(manticore_command_delete_count{pod=\"$pod\"}[1m]))",
     "legendFormat": "delete"
    },
    {
     "expr": "sum(rate(manticore_command_ping_count{pod=\"$pod\"}[1m]))",
     "legendFormat": "ping"
    },
    {
     "expr": "sum(rate(manticore_command_sphinxql_count{pod=\"$pod\"}[1m]))",
     "legendFormat": "sphinxql"
    },
    {
     "expr": "sum(rate(manticore_command_flushattrs_count{pod=\"$pod\"}[1m]))",
     "legendFormat": "flushattrs"
    },
    {
     "expr": "sum(rate(manticore_command_status_count{pod=\"$pod\"}[1m]))",
     "legendFormat": "status"
    },
    {
     "expr": "sum(rate(manticore_command_persist_count{pod=\"$pod\"}[1m]))",
     "legendFormat": "persist"
    },
    {
     "expr": "sum(rate(manticore_command_keywords_count{pod=\"$pod\"}[1m]))",
     "legendFormat": "keywords"
    },
    {
     "expr": "sum(rate(manticore_command_update_count{pod=\"$pod\"}[1m]))",
     "legendFormat": "update"
    },
    {
     "expr": "sum(rate(manticore_command_excerpt_count{pod=\"$pod\"}[1m]))",
     "legendFormat": "excerpt"
    },
    {
     "expr": "sum(rate(manticore_command_search_count{pod=\"$pod\"}[1m]))",
     "legendFormat": "search"
    }
   ]
  },
  {
   "title": "Total found rows",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum(manticore_found_rows_1min{pod=\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query time per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(manticore_query_wall_seconds{pod=\"$pod\"}[1m])",
     "legendFormat": "Query wall (1 min)"
    }
   ]
  },
  {
   "title": "Threads count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "manticore_workers_total_count{pod=\"$pod\"}",
     "legendFormat": "worker threads"
    },
    {
     "expr": "manticore_thread_count{pod=\"$pod\"}",
     "legendFormat": "active threads"
    }
   ]
  },
  {
   "title": "Killed rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(manticore_killed_rate{pod=\"$pod\"}) by (index)",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Query cache queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "manticore_qcache_cached_queries_count{pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Query cache hits count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "manticore_qcache_hits_count{pod=\"$pod\"} / manticore_queries_count{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Query cache size (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "manticore_qcache_used_bytes{pod=\"$pod\"}/1024/1024"
    }
   ]
  }
 ]
}